spring:
  application:
    name: givu

  datasource:
    url: jdbc:postgresql://localhost:5432/givudb
    username: postgres
    password: d107password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # create, create-drop, validate ??? ??? ?? ??
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
